// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFZCc9FKnjbPQZZvFWVfmwCOwgYoiNIM',
    appId: '1:933620950170:web:df7eaafc1f4e50f0c6ab23',
    messagingSenderId: '933620950170',
    projectId: 'docwise-72d23',
    authDomain: 'docwise-72d23.firebaseapp.com',
    storageBucket: 'docwise-72d23.appspot.com',
    measurementId: 'G-ETQJ80NDED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2geC_eVM6SDPxHeKVZTz7En6ZCBdcHBk',
    appId: '1:933620950170:android:f81fbcedca89c5a0c6ab23',
    messagingSenderId: '933620950170',
    projectId: 'docwise-72d23',
    storageBucket: 'docwise-72d23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Cu3ujR1T3W9shyiJm2U6on4jBb9OjuI',
    appId: '1:933620950170:ios:efc7744022337e88c6ab23',
    messagingSenderId: '933620950170',
    projectId: 'docwise-72d23',
    storageBucket: 'docwise-72d23.appspot.com',
    iosBundleId: 'com.example.docwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Cu3ujR1T3W9shyiJm2U6on4jBb9OjuI',
    appId: '1:933620950170:ios:efc7744022337e88c6ab23',
    messagingSenderId: '933620950170',
    projectId: 'docwise-72d23',
    storageBucket: 'docwise-72d23.appspot.com',
    iosBundleId: 'com.example.docwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOFZCc9FKnjbPQZZvFWVfmwCOwgYoiNIM',
    appId: '1:933620950170:web:2e6948ad715fb84dc6ab23',
    messagingSenderId: '933620950170',
    projectId: 'docwise-72d23',
    authDomain: 'docwise-72d23.firebaseapp.com',
    storageBucket: 'docwise-72d23.appspot.com',
    measurementId: 'G-YL04D4LCZQ',
  );
}
